# This Docker Compose file can be used to quickly bootup Dgraph Zero
# and Alpha in different Docker containers.

# It mounts /tmp/data on the host machine to /dgraph within the
# container. You will need to change /tmp/data to a more appropriate location.
# Run `docker-compose up` to start Dgraph.

version: "3.2"
services:
  dgraph:
    image: dgraph/standalone:latest
    ports:
      - 8080:8080
  ratel:
    image: dgraph/ratel:latest
    ports:
      - 8000:8000
